"""Add trip season/weather fields

Revision ID: 30eead9ac86d
Revises: 
Create Date: 2025-12-11 16:47:21.237658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30eead9ac86d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_category'), ['category'], unique=False)

    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('avg_temp_c', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('precip_mm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('snowfall_mm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weather_source', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.alter_column('temp_profile',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.alter_column('temp_profile',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('weather_source')
        batch_op.drop_column('snowfall_mm')
        batch_op.drop_column('precip_mm')
        batch_op.drop_column('avg_temp_c')
        batch_op.drop_column('season')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_category'))

    # ### end Alembic commands ###
